[package]
name = "chitose"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "*", default-features = false, features = [
  "rustls-tls",
  "cookies",
  "gzip",
] }
# tokio = { version = "*", features = ["macros", "rt"] }
toml = { version = "*" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
